// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:chevronRight': typeof import('virtual:vite-icons/akar-icons/chevron-right')['default']
    'AkarIcons:codepenFill': typeof import('virtual:vite-icons/akar-icons/codepen-fill')['default']
    'AkarIcons:dribbbleFill': typeof import('virtual:vite-icons/akar-icons/dribbble-fill')['default']
    'AkarIcons:githubOutlineFill': typeof import('virtual:vite-icons/akar-icons/github-outline-fill')['default']
    'AkarIcons:instagramFill': typeof import('virtual:vite-icons/akar-icons/instagram-fill')['default']
    'AkarIcons:linkedinFill': typeof import('virtual:vite-icons/akar-icons/linkedin-fill')['default']
    'AntDesign:heartFilled': typeof import('virtual:vite-icons/ant-design/heart-filled')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    EvaTwitterOutline: typeof import('virtual:vite-icons/eva/twitter-outline')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    'IconParkOutline:sunOne': typeof import('virtual:vite-icons/icon-park-outline/sun-one')['default']
    'Il:moon': typeof import('virtual:vite-icons/il/moon')['default']
    LaVolleyballBall: typeof import('virtual:vite-icons/la/volleyball-ball')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarLink: typeof import('./src/components/SidebarLink.vue')['default']
    SidebarLinks: typeof import('./src/components/SidebarLinks.vue')['default']
    SideBarLinks: typeof import('./src/components/SideBarLinks.vue')['default']
  }
}

export { }
